# https://docs.docker.com/compose/compose-file/
version: "3"

services:

  starships:
    build:
      context: .
      dockerfile: Dockerfile
    image: "starships:latest"
    ports:
    - "8443:8443"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - space-net
    depends_on:
    - mysql

  mysql:
    hostname: "mysql"
    image: "mysql:5.6"
    ports:
    - "3306:3306"
    volumes:
    - mysql_volume:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=s3cur1ty@maks
    - MYSQL_DATABASE=space
    networks:
      space-net:

networks:
  space-net:

volumes:
  mysql_volume: