apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
    kubernetes.io/ingress.allow-http: "false"
  labels:
    io.kompose.service: starships
  name: starships
spec:
  ports:
  - name: "8443"
    port: 8443
    targetPort: 8443
  selector:
    io.kompose.service: starships
status:
  loadBalancer: {}
