apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: starships
  name: starships
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: starships
    spec:
      containers:
        - image: starships:latest
          name: starships
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          imagePullPolicy: Never
          ports:
            - containerPort: 8443
          volumeMounts:
            - mountPath: "/app"
              name: spacekey
              readOnly: true
      volumes:
        - name: spacekey
          secret:
            secretName: spacekey
      restartPolicy: Always
  selector:
    matchLabels:
      io.kompose.service: starships